# .github/workflows/convert-to-pdf.yml

name: Docs to PDF

on:
  push:
    branches:
      - main

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          images_dir: docs/images
          image_import: ./images
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: converttopdf
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate random tag name
        id: tag
        run: |
          TAG_NAME="release-$(date +'%Y%m%d%H%M%S')-$(openssl rand -hex 6)"
          echo "Generated tag: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

      - name: Create release
        uses: gh-actions/create-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          release_name: Release ${{ env.tag_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download "docs" artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: ./downloaded_docs

      - name: List downloaded files
        run: |
          echo "Listing files in the downloaded docs directory:"
          ls -R ./downloaded_docs

      - name: Upload artifact to release
        uses: gh-actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./downloaded_docs/pdfs/*
          asset_name: docs-pdf.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

